[buildPlans.iosevka-custom]
family = "Iosevka Custom"
spacing = "term"
noLigation = true
exportGlyphNames = false
noCvSs = true

[buildPlans.iosevka-custom.variants.design]
# 稍微圆润的线条
capital-k = "curly-serifless" # K
capital-v = "curly-serifless" # V
capital-w = "curly-serifless" # W
k = "curly-serifless"
v = "curly-serifless"
w = "curly-serifless"
lower-lambda = 'curly-tailed-turn' # λ

# 垂直位置
asterisk = "penta-low" # *居中
caret = "low" # ^偏下
underscore = "above-baseline" # _偏上

four = "closed-serifless" # 4开口封闭
capital-g = "toothless-corner-serifless-hooked" # G
capital-q = "crossing-baseline" # Q
l = "serifed-semi-tailed" # l撬棍
six = "closed-contour"	# 6大弯钩
dollar = "through-cap" # $缩短
number-sign = "slanted" # 偏斜
percent = "rings-continuous-slash" # %完全连接
